Comment out unused variable (#2347)
With the 17.14 release of Visual Studio 2022, I see the following error:
```
...\src\GraphingImpl\Mocks\Graph.h(47,47): warning C4100: 'variableName': unreferenced parameter [...\src\GraphingImpl\GraphingImpl.vcxproj
...
...\src\GraphingImpl\Mocks\Graph.h(47,47): error C2220: the following warning is treated as an error [...\src\GraphingImpl\GraphingImpl.vcxproj
```
Comment out the unused variable to resolve this.